services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          '/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "YourStrong@Passw0rd" -Q "SELECT 1" -C || exit 1',
        ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  backend:
    build:
      context: ./backend/ProductApi
      dockerfile: Dockerfile
    container_name: product-api
    depends_on:
      sql-server:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Server=sql-server,1433;Database=ProductCrudDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=true"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend/product-crud-client
      dockerfile: Dockerfile
    container_name: product-frontend
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://localhost:8080/api/products
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
